apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    tags: "exec"
  name: "amqp-content-router"
  labels:
    app: "amqp-content-router"
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "amqp-content-router-${env}"
      namespace: "vrt-intake"
      labels:
        app: "amqp-content-router"
        app.kubernetes.io/component: "amqp-content-router-${env}"
        app.kubernetes.io/instance: "amqp-content-router-${env}"
        app.kubernetes.io/name: "amqp-content-router"
        app.kubernetes.io/part-of: "amqp-content-router"
        app.openshift.io/runtime: "amqp-content-router"
        app.openshift.io/runtime-version: "${env}"
        env: ${env}
    spec:
      ports:
        - protocol: TCP
          port: ${{svc_port}}
          targetPort: ${{svc_port}}
          name: http
      selector:
        app: "amqp-content-router-${env}"
      clusterIP:
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: "*"
        image.openshift.io/triggers: >-
          [{'from':{'kind':'ImageStreamTag','name':'amqp-content-router:${env}','namespace':'vrt-intake'},'fieldPath':'spec.template.spec.containers[?(@.name==\'amqp-content-router-${env}\')].image','pause':'false'}]
      name: "amqp-content-router-${env}"
      namespace: "vrt-intake"
      labels:
        app: "amqp-content-router"
        app.kubernetes.io/component: "amqp-content-router-${env}"
        app.kubernetes.io/instance: "amqp-content-router-${env}"
        app.kubernetes.io/name: "amqp-content-router"
        app.kubernetes.io/part-of: "amqp-content-router"
        app.openshift.io/runtime: "amqp-content-router"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    spec:
      replicas: 0
      selector:
        matchLabels:
          app: "amqp-content-router-${env}"
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: "amqp-content-router-${env}"
            deploymentconfig: "amqp-content-router-${env}"
            env: ${env}
          annotations:
            openshift.io/generated-by: OpenShiftWebConsole
        spec:
          containers:
            - name: "amqp-content-router-${env}"
              terminationMessagePath: /dev/termination-log
              resources:
                limits:
                  cpu: '${cpu_limit}m'
                  memory: '${memory_limit}Mi'
                requests:
                  cpu: '${cpu_requested}m'
                  memory: '${memory_requested}Mi'
              ports:
                - containerPort: ${{svc_port}}
                  protocol: TCP
              imagePullPolicy: IfNotPresent
              terminationMessagePolicy: File
              envFrom:
                - configMapRef:
                    name: "amqp-content-router-${env}"
              image: >-
                image-registry.openshift-image-registry.svc:5000/vrt-intake/amqp-content-router:${env}
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      revisionHistoryLimit: 10
      progressDeadlineSeconds: 600
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: "amqp-content-router-${env}"
      namespace: "vrt-intake"
      labels:
        app: "amqp-content-router"
        app.kubernetes.io/component: "amqp-content-router-${env}"
        app.kubernetes.io/instance: "amqp-content-router-${env}"
        app.kubernetes.io/name: "amqp-content-router"
        app.kubernetes.io/part-of: "amqp-content-router"
        app.openshift.io/runtime: "amqp-content-router"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    data:
      RABBIT_MQ_USER: some_value
      RABBIT_MQ_PASSWD: some_value
      RABBIT_MQ_HOST: some_value
      RABBITMQ_QUEUE: some_value
      RABBITMQ_EXCHANGE: some_value
parameters:
  - name: env
    value: "env"
  - name: "memory_requested"
    value: "128"
  - name: "memory_limit"
    value: "328"
  - name: "cpu_requested"
    value: "100"
  - name: "cpu_limit"
    value: "300"
  - name: "svc_port"
    value: "8080"