kind: Deployment
apiVersion: apps/v1
metadata:
  name: amqp-content-router-int
  namespace: vrt-intake
  labels:
    app: amqp-content-router
    app.kubernetes.io/component: amqp-content-router-int
    app.kubernetes.io/instance: amqp-content-router-int
    app.kubernetes.io/name: amqp-content-router
    app.kubernetes.io/part-of: amqp-content-router
    app.openshift.io/runtime: amqp-content-router
    app.openshift.io/runtime-version: int
    env: int
spec:
  replicas: 0
  selector:
    matchLabels:
      app: amqp-content-router-int
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: amqp-content-router-int
        deploymentconfig: amqp-content-router-int
        env: int
    spec:
      containers:
        - name: amqp-content-router-int
          image: >-
            image-registry.openshift-image-registry.svc:5000/vrt-intake/amqp-content-router:int
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: amqp-content-router-int
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
