pipeline {
    agent {
        kubernetes {
            defaultContainer 'default'
            yaml '''\
        apiVersion: v1
        kind: Pod
        metadata:
          labels:
            component: builder
            lang: python
            app: amqp-content-router
        spec:
          containers:
          - name: default
            image: python:3.7
            command:
            - cat
            tty: true
            imagePullPolicy: Always
          - name: oc
            image: image-registry.openshift-image-registry.svc:5000/ci-cd/py:3.7
            command:
            - cat
            tty: true
            imagePullPolicy: Always
        '''.stripIndent()
        }
    }
    options {
        timeout(time: 45, unit: 'MINUTES')
    }
    stages {
        stage('Checkout code') {
            steps {
                checkout scm
            }
        }
        stage('Test code') {
            steps {
                // test
            }
        }
        stage('Build code') {
            steps {
                container('oc') {
                    sh 'make -f ./openshift/Makefile start-build'
                }
            }
        }
    }
}
